### ISSUE TITLE
Documentation may need updating for Laravel 11

### ISSUE THREAD

**Issue by steveparks** [mitydigital/statamic-scheduled-cache-invalidator#11]
In the documentation for this addon at https://docs.mity.com.au/scheduled-cache-invalidator/how-to-use it refers to adding a command to ```app/Console/Kernel.php```

I'm a complete newbie to Statamic and Laravel, so may have this wrong, but think this may need to be updated for Laravel 11, where I guess a command will need to be added to ```routes/console.php```. The command may need to be formatted differently too?

**Comment by martyf** [comment]
Thanks for this pickup 🎉

The syntax can stay the same, just needs to be in the new `routes/console.php` file. This has been updated in the docs.
