### ISSUE TITLE
[Bug] Orderable collections with publish dates enabled causes exception

### ISSUE THREAD

**Issue by dries-dekeersgieter** [mitydigital/statamic-scheduled-cache-invalidator#7]
I've noticed an issue when a collection is configured as follows:
- has publish dates enabled
- is orderable

The NowScope will be applied, comparing the date on the 'order' field, which throws an exception.

**Comment by martyf** [comment]
Can you please provide more detail (including the exception) and a link to a repo that replicates the issue.

**Comment by dries-dekeersgieter** [comment]
I've created a sample project:
https://github.com/insight-media/statamic-scheduled-cache-invalidator-issue

**Comment by martyf** [comment]
Thanks for the project - this was great to play with to nail this down.

It is to do with what Statamic does with ordered and dated collections - and it falls back to the order index instead of the date field. 

2.0.3 (just tagged) will address this.

Let me know how you go.

**Comment by dries-dekeersgieter** [comment]
Thanks @martyf !
Works perfectly.

**Comment by martyf** [comment]
Huzzah! Glad it's sorted.
